export const ADD_TO_CART = "addToCart"
export const REMOVE_FROM_CART = "removeFromCart"
export const CLEAR_CART = "clearCart"
export const UPDATE_CONTACT = "updateContact"
export const BUY_COURSE = "buyCourse"
export const CREATE_COURSE = "createCourse"
export const CRUD_OPERATION = "crudOperation"
